model_type: nbf
test_batch_size: 64

n_entities: 14541
n_relations: 237

output_dir: ~/experiments/
dataset:
  class: FB15k237
  path: ./data

task:
  class: KnowledgeGraphCompletion
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: yes
    remove_one_hop: yes
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  sample_weight: no
  full_batch_eval: yes

optimizer:
  class: Adam
  lr: 5.0e-3


metric: mrr


engine:
  batch_size: 64
