output_dir: ~/experiments/
model_type: nbf
test_batch_size: 64
n_relations: 51
n_entities: 93773
dataset:
  class: OGBLBioKG
  path: ./data

task:
  class: KnowledgeGraphCompletionOGB
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: yes
    remove_one_hop: yes
  criterion: bce
  evaluator:
    class: Evaluator
    name: ogbl-biokg
  num_negative: 0
  strict_negative: yes
  heterogeneous_negative: yes
  adversarial_temperature: 0.5
  sample_weight: no

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  batch_size: 8
  log_interval: 10

train:
  num_epoch: 10
  batch_per_epoch: 200

metric: mrr
fast_test: 1000