model_type: arm_convolution
dataset: 
  class: WN18RR
  path: ./data
save_model: True  

epochs: 1000

embedding_dimension: 150 
lr: 0.008909 
weight_decay: 2
prediction_smoothing: 1.0e-30
label_smoothing: 0.1 
dropout: 0.02927 
factor: 0.5
lr_patience: 10
prior_type: learnable
m: 256
kernel_size: 3