model_type: nbf
test_batch_size: 32
seed: 17
n_relations: 11
n_entities: 40943

dataset:
  class: WN18RR
  path: ./data

task:
  class: KnowledgeGraphCompletion
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: no
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  sample_weight: no
  full_batch_eval: yes

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  batch_size: 32

train:
  num_epoch: 20

metric: mrr 
